# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTdOQO84pYsUHmbdyrEDpZ_8SpZYi-W6
"""

import os
import requests
import re
import sys
from bs4 import BeautifulSoup  # Import BeautifulSoup library

# Function to get the HTML source text of the Medium article
def get_page():
    global url

    url = input("Enter URL of a Medium article: ")  # Ask the user to input the URL

    # Handling possible error
    if not re.match(r'https?://medium.com/.+', url):
        print('Please enter a valid website, or make sure it is a Medium article.')
        sys.exit(1)

    res = requests.get(url)  # Call get method in requests object and collect it in res

    res.raise_for_status()
    soup = BeautifulSoup(res.text, 'html.parser')
    return soup

# Function to remove all the HTML tags and replace some with specific strings
def clean(text):
    rep = {"<br>": "\n", "<br/>": "\n", "<li>":  "\n"}
    rep = dict((re.escape(k), v) for k, v in rep.items())
    pattern = re.compile("|".join(rep.keys()))
    text = pattern.sub(lambda m: rep[re.escape(m.group(0))], text)
    text = re.sub(r'\<(.*?)\>', '', text)
    return text

def collect_text(soup):
    text = f'URL: {url}\n\n'
    para_text = soup.find_all('p')
    print(f"Paragraphs text = \n {para_text}")
    for para in para_text:
        text += f"{para.text}\n\n"
    return text

# Function to save the file in the current directory
def save_file(text):
    if not os.path.exists('./scraped_articles'):
        os.mkdir('./scraped_articles')
    name = url.split("/")[-1]
    print(name)
    fname = f'scraped_articles/{name}.txt'

    # Write the file using with
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(text)

    print(f'File saved in directory {fname}')

if __name__ == '__main__':
    text = collect_text(get_page())
    save_file(text)
    # Instructions to Run this Python code
    # Give url as https://medium.com/@subashgandyer/papa-what-is-a-neural-network-c5e5cc427c7